###
POST http://localhost:8081/login
Content-Type: application/json

{
  "login": "Lusi@mail.ru",
  "password": "123"
}

###

POST http://localhost:8081/cloud/file/pups.txt
Content-Type: application/json

{
  "filename": "pups-lapups.txt"
}

###

GET http://localhost:8081/cloud/file/pups.txt

###

DELETE http://localhost:8081/cloud/file/pups-lapups.txt

###

